INSERT INTO PRODUCT(CATEGORY, PRODUCT_NAME, LOCATION_ID) VALUES('Sports', 'Arsenal TV', 'LONDON');
INSERT INTO PRODUCT(CATEGORY, PRODUCT_NAME, LOCATION_ID) VALUES('Sports', 'Chelsea TV', 'LONDON');
INSERT INTO PRODUCT(CATEGORY, PRODUCT_NAME, LOCATION_ID) VALUES('Sports', 'Liverpool TV', 'LIVERPOOL');
INSERT INTO PRODUCT(CATEGORY, PRODUCT_NAME, LOCATION_ID) VALUES('News', 'Sky News', null);
INSERT INTO PRODUCT(CATEGORY, PRODUCT_NAME, LOCATION_ID) VALUES('News', 'Sky Sports News', null);